<section>
    <h2>Connexion</h2>
    <form>
        <fieldset>
        <label>Nom d'utilisateur/email : </label>
        <input type="email" name="loginEmail">
        </fieldset>
        
        <fieldset>
        <label>Mot de passe : </label>
        <input type="password" name="loginPassword">
        </fieldset>
        
        <input type="submit" name="login">
    </form>
</section>

<section>
    <h2>S'inscrire</h2>
    <form>
        <fieldset>
        <label>Nom d'utilisateur : </label>
        <input type="text" name="registerEmail">
        </fieldset>
        
        <fieldset>
        <label>Email : </label>
        <input type="email" name="registerEmail">
        </fieldset>
        
        <fieldset>
        <label>Mot de passe : </label>
        <input type="password" name="registerPassword">
        </fieldset>
        
        <fieldset>
        <label>Confirmer Mot de passe : </label>
        <input type="password" name="confirm-password">
        </fieldset>
        
        <input type="submit" name="register">
    </form>
</section>