<section>
    <h2>Créer une catégorie</h2>
    <form action="index.php?route=create-categories" method="POST">
        
        <fieldset>
        <label>Nom de la catégorie : </label>
        <input type="text" name="catName">
        </fieldset>
        
        <fieldset>
        <label>Description : </label>
        <input type="text" name="catDescription">
        </fieldset>
        
        <input type="submit" name="create-category">
    </form>
</section>