<section>
    <h2>Créer un salon</h2>
    <form action="index.php?route=créer-salon" method="POST">
        
        <fieldset>
        <label>Nom du salon : </label>
        <input type="text" name="roomName">
        </fieldset>
        
        <fieldset>
        <label>Description : </label>
        <input type="text" name="roomDescription">
        </fieldset>
        
        <fieldset>
        <label>Categorie : </label>
        <select name="categoryId">
            <option>-Choisissez la catégorie-</option>
            <?php 
            foreach($data as $category){ ?>
            <option value=<?= $category->getId()?>><?= $category->getName()." ".$category->getId() ?></option>
            <?php } ?>
        </select>
        </fieldset>
        
        <input type="submit" name="create-room">
    </form>
</section>