<section id="createCatForm">
    <section>
    <h2>Créer une catégorie</h2>
    <form action="index.php?route=créer-categorie" method="POST">
        
        <fieldset>
        <label>Nom de la catégorie : </label>
        <input type="text" name="catName">
        </fieldset>
        
        <fieldset>
        <label>Description : </label>
        <input type="text" name="catDescription">
        </fieldset>
        
        <input type="submit" name="create-category" value="Créer une catégorie">
    </form>
    </section>
    <section>
        <figure>
            <img src="./assets/images/logoDistorsion.png" alt="logo">
        </figure>
    </section>
</section>