<section>
    <h2>Si vous n'avez pas de compte</h2>
    <p>Créez-en un !</p>
    <a href="https://vincentollivier.sites.3wa.io/00-perso/projet-distortion/res03-php-ProjetDistorsion/Distorsion/index.php?route=créer-compte"><button name="register" id="loginButton">S'inscrire</button></a>
</section>
<section>
    <h2>Déjà un compte ?</h2>
    <a href="https://vincentollivier.sites.3wa.io/00-perso/projet-distortion/res03-php-ProjetDistorsion/Distorsion/index.php?route=connexion"><button name="login" id="loginButton">Se Connecter</button></a>
</section>  