<section id="loginForm">
    <section>
    <h2>Connexion</h2>
    <form action="index.php?route=connexion" method="POST">
        
        <fieldset>
        <label>Email : </label>
        </fieldset>
        
        <fieldset>
        <input type="email" name="loginEmail">
        </fieldset>
        
        <fieldset>
        <label>Mot de passe : </label>
        </fieldset>
        
        <fieldset>
        <input type="password" name="loginPassword">
        </fieldset>
        
        <input type="submit" name="login" id="loginButton">
    </form>
    </section>
    <section>
        <figure>
            <img src="./assets/images/logoDistorsion.png" alt="logo">
        </figure>
    </section>
</section>