<section>
    <h2>Connexion</h2>
    <form action="index.php?route=connexion" method="POST">
        <fieldset>
        <label>Nom d'utilisateur/email : </label>
        <input type="email" name="loginEmail">
        </fieldset>
        
        <fieldset>
        <label>Mot de passe : </label>
        <input type="password" name="loginPassword">
        </fieldset>
        
        <input type="submit" name="login">
    </form>
</section>