<section>
    <h2>S'inscrire</h2>
    <form action="index.php?route=créer-compte" method="POST">

        <fieldset>
        <label>Nom d'utilisateur : </label>
        <input type="text" name="registerUsername">
        </fieldset>

        <fieldset>
        <label>Email : </label>
        <input type="email" name="registerEmail">
        </fieldset>
        
        <fieldset>
        <label>Mot de passe : </label>
        <input type="password" name="registerPassword">
        </fieldset>
        
        <fieldset>
        <label>Confirmer Mot de passe : </label>
        <input type="password" name="confirmPassword">
        </fieldset>
        
        <input type="submit" name="S'inscrire">
    </form>
</section>