<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="Vincent Ollivier, Arnaud Deletre" />
    <meta name="referrer" content="origin" />
    <meta name="title" content="Distorsion">
    <meta name="keywords" content="">
    <meta property="og:site_name" content="Distorsion">
    <meta property="og:title" content="Le Discord du pauvre">
    <meta property="og:type" content="article">
    <meta property="og:url" content="">
    <meta property="og:image" content="">
    <meta property="og:description" content="Distorsion, chattez avec vos amis !">
    <meta property="og:locale" content="fr_FR">
    <link rel="stylesheet" href="./assets/styles/css/style.css">
    <title>Distorsion</title>
</head>

<body>
    
    <header>
        <?php require 'partials/_header.phtml'; ?>
    </header>    
    
    <main>
        <aside>
            <?php require "partials/_aside.phtml"; ?>
        </aside>
        <section>
            <?php 
                require "views/templates/".$template.".phtml"; 
                require "views/templates/create-category.phtml";
                require "views/templates/create-room.phtml";
            ?>
            
        </section>
    </main>
    
    <footer>
        <?php require 'partials/_footer.phtml'; ?>
    </footer>

</body>

</html>