<section>
    <h2>S'inscrire</h2>
    <form>
        <fieldset>
        <label>Nom d'utilisateur/email : </label>
        <input type="email" name="email">
        </fieldset>
        
        <fieldset>
        <label>Mot de passe : </label>
        <input type="password" name="password">
        </fieldset>
        
        <fieldset>
        <label>Confirmer Mot de passe : </label>
        <input type="password" name="confirm-password">
        </fieldset>
        
        <input type="submit" name="register">
    </form>
</section>