<footer>
    <h2>FOOTER</h2>
    <ul>
        <li><a href="https://vincentollivier.sites.3wa.io/00-perso/projet-distortion/res03-php-ProjetDistorsion/Distorsion/index.php">Accueil</a></li>
        <li><a href="https://vincentollivier.sites.3wa.io/00-perso/projet-distortion/res03-php-ProjetDistorsion/Distorsion/index.php">S'enregistrer</a></li>
        <li><a href="https://vincentollivier.sites.3wa.io/00-perso/projet-distortion/res03-php-ProjetDistorsion/Distorsion/index.php">Se connecter</a></li>
    </ul>
    
</footer>