<header>
    <h2>HEADER</h2>
    <ul>
        <li><a href="https://vincentollivier.sites.3wa.io/00-perso/projet-distortion/res03-php-ProjetDistorsion/Distorsion/index.php?route=accueil">Accueil</a></li>
        <li><a href="https://vincentollivier.sites.3wa.io/00-perso/projet-distortion/res03-php-ProjetDistorsion/Distorsion/index.php?route=créer-compte">créer-compte</a></li>
        <li><a href="https://vincentollivier.sites.3wa.io/00-perso/projet-distortion/res03-php-ProjetDistorsion/Distorsion/index.php?route=connexion">connexion</a></li>
        <li><a href="https://vincentollivier.sites.3wa.io/00-perso/projet-distortion/res03-php-ProjetDistorsion/Distorsion/index.php?route=bienvenu">bienvenu</a></li>
    </ul>
    
</header>