<h2>HEADER</h2>
    <ul>
        <li><a href="index.php?route=accueil">Accueil</a></li>
        <li><a href="index.php?route=créer-compte">créer-compte</a></li>
        <li><a href="index.php?route=connexion">connexion</a></li>
        <li><a href="index.php?route=bienvenu">bienvenu</a></li>
        <li><a href="index.php?route=créer-categorie">creer cat</a></li>
        <li><a href="index.php?route=créer-salon">creer room</a></li>
    </ul>
<h2><?php echo  "Bienvenue ".$_SESSION["username"] ?></h2>
